"""Deterministic glyph set generation.

A glyph is a ``cell_px x cell_px`` binary bitmap drawn at native resolution:
one bitmap pixel is one screen pixel, so a glyph is never resampled.

Generation, for a given (glyph_count, cell_px):

1. **Candidate pool.** Draw integer noise fields from the SHA-256 keystream
   (seed ``GLYPH_POOL_SEED``), smooth them with an integer binomial kernel, and
   threshold each at its rank so exactly ``cell_px**2 // 2`` pixels are ink
   (constant weight). Reject patterns with an *isolated pixel* - a pixel whose
   in-grid 4-neighbours all have the opposite value - because a single-pixel
   feature is below what the camera's optics can resolve. Deduplicate, keep
   the first ``GLYPH_POOL_SIZE`` survivors.
2. **Selection.** Choose ``glyph_count`` patterns maximising the minimum
   pairwise Hamming distance (max-min dispersion). Greedy farthest-point
   construction from ``GLYPH_SELECT_RESTARTS`` deterministic starts, each
   followed by a swap local search. Ties are broken by fewer pairs at the
   minimum distance, then by larger total distance.
3. **Canonical order.** The chosen patterns are sorted by their row-major bit
   string, which fixes the glyph index -> bitmap mapping.

Everything is integer arithmetic with explicit tie-breaking, so the result is
identical on every machine. It is nevertheless cached as JSON in
``glyph_cache/`` and committed, so the set used in the thesis can never change
silently; tests/test_glyphs.py checks that the cache equals a regeneration.
"""

from __future__ import annotations

import functools
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import numpy.typing as npt

from prism_share.codec.params import (
    GLYPH_ALGORITHM_VERSION,
    GLYPH_POOL_MAX_DRAWS_PER_CANDIDATE,
    GLYPH_POOL_SEED,
    GLYPH_POOL_SIZE,
    GLYPH_SELECT_RESTARTS,
    GLYPH_SMOOTH_KERNEL,
    GLYPH_SMOOTH_PASSES,
    CodecParams,
)
from prism_share.codec.prng import keystream_array

CACHE_DIR = Path(__file__).parent / "glyph_cache"

BoolArray = npt.NDArray[np.bool_]
IntArray = npt.NDArray[np.int64]


@dataclass(frozen=True)
class GlyphSet:
    """A chosen glyph set and the quality figures reported in the thesis."""

    glyph_count: int
    cell_px: int
    patterns: BoolArray  # (glyph_count, cell_px, cell_px), True = ink
    min_hamming: int
    pairs_at_min: int
    pool_size: int
    algorithm_version: int


# --------------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------------- #


def glyphs_for(params: CodecParams) -> BoolArray:
    """Glyph bitmaps for ``params``: (glyph_count, cell_px, cell_px) bool, True = ink."""
    return glyph_set(params.glyph_count, params.cell_px).patterns


@functools.lru_cache(maxsize=None)
def glyph_set(glyph_count: int, cell_px: int) -> GlyphSet:
    """Load the cached glyph set, generating and caching it only if absent.

    A cache from a different algorithm version is an error, never overwritten:
    captures made with the old glyphs would silently stop decoding.
    """
    path = cache_path(glyph_count, cell_px)
    if path.exists():
        cached = _read_cache(path)
        if cached.algorithm_version != GLYPH_ALGORITHM_VERSION:
            raise RuntimeError(
                f"{path.name} was generated by glyph algorithm v{cached.algorithm_version}, "
                f"code is v{GLYPH_ALGORITHM_VERSION}; delete the file deliberately to regenerate"
            )
        return cached
    generated = generate_glyph_set(glyph_count, cell_px)
    _write_cache(path, generated)
    return generated


def cache_path(glyph_count: int, cell_px: int) -> Path:
    return CACHE_DIR / f"glyphs_g{glyph_count}_px{cell_px}.json"


def generate_glyph_set(glyph_count: int, cell_px: int) -> GlyphSet:
    """Run the full generation algorithm (ignores the cache)."""
    pool = candidate_pool(cell_px)
    if len(pool) < glyph_count:
        raise ValueError(
            f"only {len(pool)} candidates for cell_px={cell_px}; cannot choose {glyph_count}"
        )
    flat = pool.reshape(len(pool), -1)
    chosen = select_max_min(flat, glyph_count)
    patterns = pool[chosen]
    order = sorted(range(glyph_count), key=lambda i: _bitstring(patterns[i]))
    patterns = patterns[order]
    patterns.setflags(write=False)
    min_d, at_min = min_pairwise_hamming(patterns)
    return GlyphSet(
        glyph_count=glyph_count,
        cell_px=cell_px,
        patterns=patterns,
        min_hamming=min_d,
        pairs_at_min=at_min,
        pool_size=len(pool),
        algorithm_version=GLYPH_ALGORITHM_VERSION,
    )


def min_pairwise_hamming(patterns: BoolArray) -> tuple[int, int]:
    """(minimum pairwise Hamming distance, number of pairs at that minimum)."""
    flat = patterns.reshape(len(patterns), -1)
    dist = _hamming_matrix(flat)
    upper = dist[np.triu_indices(len(flat), k=1)]
    min_d = int(upper.min())
    return min_d, int((upper == min_d).sum())


# --------------------------------------------------------------------------- #
# Candidate pool
# --------------------------------------------------------------------------- #


def candidate_pool(cell_px: int) -> BoolArray:
    """Distinct constant-weight candidate patterns, (P, cell_px, cell_px) bool."""
    n_pixels = cell_px * cell_px
    weight = n_pixels // 2
    seen: set[bytes] = set()
    pool: list[BoolArray] = []
    max_draws = GLYPH_POOL_SIZE * GLYPH_POOL_MAX_DRAWS_PER_CANDIDATE
    for draw in range(max_draws):
        noise = keystream_array(
            GLYPH_POOL_SEED, f"glyph-pool-px{cell_px}", n_pixels, index=draw
        ).astype(np.int64)
        field = _smooth(noise.reshape(cell_px, cell_px))
        pattern = _threshold_rank(field, weight)
        if _has_isolated_pixel(pattern):
            continue
        key = np.packbits(pattern).tobytes()
        if key in seen:
            continue
        seen.add(key)
        pool.append(pattern)
        if len(pool) == GLYPH_POOL_SIZE:
            break
    return np.array(pool, dtype=bool)


def _smooth(field: IntArray) -> IntArray:
    """Separable integer convolution with GLYPH_SMOOTH_KERNEL, edge-replicated."""
    kernel = np.array(GLYPH_SMOOTH_KERNEL, dtype=np.int64)
    radius = len(kernel) // 2
    out = field
    for _ in range(GLYPH_SMOOTH_PASSES):
        for axis in (0, 1):
            padded = np.pad(out, [(radius, radius) if a == axis else (0, 0) for a in (0, 1)], mode="edge")
            acc = np.zeros_like(out)
            for offset, weight in enumerate(kernel):
                window = [slice(None), slice(None)]
                window[axis] = slice(offset, offset + out.shape[axis])
                acc += weight * padded[tuple(window)]
            out = acc
    return out


def _threshold_rank(field: IntArray, weight: int) -> BoolArray:
    """Mark the ``weight`` largest values as ink; ties go to the lower pixel index."""
    flat = field.ravel()
    order = np.argsort(-flat, kind="stable")
    ink = np.zeros(flat.shape, dtype=bool)
    ink[order[:weight]] = True
    return ink.reshape(field.shape)


def _has_isolated_pixel(pattern: BoolArray) -> bool:
    """True if some pixel differs from all of its in-grid 4-neighbours."""
    same_count = np.zeros(pattern.shape, dtype=np.int64)
    same_count[1:, :] += pattern[1:, :] == pattern[:-1, :]
    same_count[:-1, :] += pattern[:-1, :] == pattern[1:, :]
    same_count[:, 1:] += pattern[:, 1:] == pattern[:, :-1]
    same_count[:, :-1] += pattern[:, :-1] == pattern[:, 1:]
    return bool((same_count == 0).any())


# --------------------------------------------------------------------------- #
# Max-min selection
# --------------------------------------------------------------------------- #


def select_max_min(flat: BoolArray, k: int) -> list[int]:
    """Indices of ``k`` rows of ``flat`` with (heuristically) maximal min Hamming distance."""
    dist = _hamming_matrix(flat)
    n = len(flat)
    best: list[int] | None = None
    best_score: tuple[int, int, int] | None = None
    restarts = min(GLYPH_SELECT_RESTARTS, n)
    for restart in range(restarts):
        start = (restart * n) // restarts
        chosen = _local_search(dist, _greedy(dist, start, k))
        score = _score(dist, chosen)
        if best_score is None or score > best_score:
            best, best_score = chosen, score
    assert best is not None
    return best


def _hamming_matrix(flat: BoolArray) -> IntArray:
    ints = flat.astype(np.int64)
    overlap = ints @ ints.T
    weights = ints.sum(axis=1)
    return weights[:, None] + weights[None, :] - 2 * overlap


def _greedy(dist: IntArray, start: int, k: int) -> list[int]:
    chosen = [start]
    min_to_chosen = dist[start].copy()
    min_to_chosen[start] = -1
    while len(chosen) < k:
        nxt = int(np.argmax(min_to_chosen))  # first maximum -> lowest index
        chosen.append(nxt)
        min_to_chosen = np.minimum(min_to_chosen, dist[nxt])
        min_to_chosen[chosen] = -1
    return chosen


def _score(dist: IntArray, chosen: list[int]) -> tuple[int, int, int]:
    """Lexicographic objective: (min distance, -pairs at min, total distance)."""
    sub = dist[np.ix_(chosen, chosen)]
    upper = sub[np.triu_indices(len(chosen), k=1)]
    min_d = int(upper.min())
    return min_d, -int((upper == min_d).sum()), int(upper.sum())


def _local_search(dist: IntArray, chosen: list[int]) -> list[int]:
    """Best-improvement single swaps until no swap improves the objective."""
    chosen = list(chosen)
    current = _score(dist, chosen)
    n = len(dist)
    improved = True
    while improved:
        improved = False
        for slot in range(len(chosen)):
            others = chosen[:slot] + chosen[slot + 1 :]
            sub = dist[np.ix_(others, others)]
            upper = sub[np.triu_indices(len(others), k=1)]
            base_min = int(upper.min()) if len(upper) else np.iinfo(np.int64).max
            base_at_min = int((upper == base_min).sum()) if len(upper) else 0
            base_sum = int(upper.sum())

            to_others = dist[:, others]  # (n, k-1)
            new_min = np.minimum(base_min, to_others.min(axis=1))
            at_min = (to_others == new_min[:, None]).sum(axis=1)
            at_min = at_min + np.where(new_min == base_min, base_at_min, 0)
            total = base_sum + to_others.sum(axis=1)

            valid = np.ones(n, dtype=bool)
            valid[chosen] = False
            # lexsort: last key is primary. Maximise min, minimise at_min, maximise total,
            # then prefer the lowest candidate index.
            order = np.lexsort((np.arange(n), -total, at_min, -new_min))
            order = order[valid[order]]
            if not len(order):
                continue
            cand = int(order[0])
            cand_score = (int(new_min[cand]), -int(at_min[cand]), int(total[cand]))
            if cand_score > current:
                chosen[slot] = cand
                current = cand_score
                improved = True
    return chosen


# --------------------------------------------------------------------------- #
# Cache I/O
# --------------------------------------------------------------------------- #


def _bitstring(pattern: BoolArray) -> str:
    return "".join("1" if v else "0" for v in pattern.ravel())


def _write_cache(path: Path, gs: GlyphSet) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "glyph_count": gs.glyph_count,
        "cell_px": gs.cell_px,
        "algorithm_version": gs.algorithm_version,
        "min_hamming": gs.min_hamming,
        "pairs_at_min": gs.pairs_at_min,
        "pool_size": gs.pool_size,
        "patterns": [
            ["".join("1" if v else "0" for v in row) for row in pattern] for pattern in gs.patterns
        ],
    }
    path.write_text(json.dumps(doc, indent=1) + "\n", encoding="ascii")


def _read_cache(path: Path) -> GlyphSet:
    doc = json.loads(path.read_text(encoding="ascii"))
    patterns = np.array(
        [[[ch == "1" for ch in row] for row in pattern] for pattern in doc["patterns"]],
        dtype=bool,
    )
    patterns.setflags(write=False)
    return GlyphSet(
        glyph_count=int(doc["glyph_count"]),
        cell_px=int(doc["cell_px"]),
        patterns=patterns,
        min_hamming=int(doc["min_hamming"]),
        pairs_at_min=int(doc["pairs_at_min"]),
        pool_size=int(doc["pool_size"]),
        algorithm_version=int(doc["algorithm_version"]),
    )
