"""Laptop-side run definitions: what was on screen during a run.

The capture contract (docs/capture-format.md) says: the phone records the
camera, the laptop records the stimulus, and ``run_id`` is the join key. The
contract does not define the laptop-side file (the phone never reads it), so
this module defines it, and ``python -m prism_share.ingest.rundef new`` writes it::

    # experiments/runs/<run_id>.yaml
    run_id: d07_a30_lux200_oled      # must equal manifest.json's run_id
    frames: data/runs/c4_px8          # folder written by `display frames` (has frames.json)
    displayed: [3]                    # exactly ONE block_id: the static frame held for the whole capture
    condition:                        # free-form scalars; each becomes a column in the sweep
      distance_m: 0.7
      illuminance_lux: 200
    clip_check:                       # show these right after locking, before capturing
      brightest: {colour_depth: 1, cell_px: 10, frames: data/clip_check/c1_px10, frame_mean_linear: 0.4375, stops_vs_reference: 0.506}
      darkest:   {colour_depth: 4, cell_px: 4,  frames: data/clip_check/c4_px4,  frame_mean_linear: 0.2174, stops_vs_reference: -0.502}

**One run = one codec configuration = one static frame.** The frame is held for
the whole capture and never advances, so a capture can never be torn between
two frames. Frame yield is the fraction of captures that are recoverable; the
variation between captures comes from the channel (noise, rolling-shutter
phase, micro-motion), not from the stimulus changing. Content variation is
covered by running several distinct frames of a configuration, one per run.

**Clip check.** Exposure is locked on the reference frame, whose linear
luminance sits at the midpoint of the sweep, so the brightest and darkest code
configurations sit about half a stop either side of it. The reference passing
a clip check does not prove they pass. ``rundef new`` therefore records the two
extreme configurations (from the same linear-luminance table as
docs/reference_frame.md) and writes their frames, and ``display measure``
shows them right after the reference so the operator clip-checks both before
the run proceeds.

The configuration and payload come from ``frames.json``, so there is one source
of truth for what was displayed. On load, the displayed frame's ground truth is
regenerated by re-encoding the payload, and it must hash to what ``frames.json``
recorded at display time - so a codec change between capture and analysis
cannot go unnoticed. Relative paths resolve against the repository root (the
parent of experiments/).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import numpy.typing as npt
import yaml

from prism_share.codec.encoder import encode_frames, save_frames
from prism_share.codec.params import CodecParams
from prism_share.codec.prng import keystream
from prism_share.ingest.manifest import RunRejected
from prism_share.transmit.display import image_sha256

IntArray = npt.NDArray[np.int64]
DEFAULT_RUNS_DIR = Path("experiments") / "runs"
DEFAULT_CLIP_CHECK_DIR = Path("data") / "clip_check"
CLIP_CHECK_ROLES = ("brightest", "darkest")
_CLIP_CHECK_KEYS = ("colour_depth", "cell_px", "frames", "frame_mean_linear", "stops_vs_reference")
#: Decimals written for luminance and stops in a run definition (display only).
_LUMINANCE_DECIMALS, _STOPS_DECIMALS = 5, 3
#: Payload of clip-check frames: deterministic, identical for every run.
_CLIP_PAYLOAD_DOMAIN = "clip-check-payload"


@dataclass(frozen=True)
class DisplayedFrame:
    block_id: int
    frame_index: int
    """The value drawn in this frame's index band."""
    file: str
    glyphs: IntArray
    colours: IntArray


@dataclass(frozen=True)
class ClipCheck:
    """One extreme configuration the operator clip-checks after locking."""

    role: str
    colour_depth: int
    cell_px: int
    frames_dir: Path
    frame_mean_linear: float
    stops_vs_reference: float


@dataclass(frozen=True)
class RunDefinition:
    run_id: str
    path: Path
    frames_dir: Path
    params: CodecParams
    frame: DisplayedFrame
    """The one static frame held for the whole capture."""
    condition: dict[str, Any]
    clip_check: tuple[ClipCheck, ...]

    @property
    def by_index(self) -> dict[int, DisplayedFrame]:
        """Ground truth by index-band value. One entry: a capture carrying any other index
        did not show this run's frame and is never matched to it."""
        return {self.frame.frame_index: self.frame}

    def condition_columns(self) -> dict[str, Any]:
        return {f"condition_{k}": v for k, v in sorted(self.condition.items())}


def run_definition_path(run_id: str, runs_dir: Path = DEFAULT_RUNS_DIR) -> Path:
    return runs_dir / f"{run_id}.yaml"


def _root(runs_dir: Path) -> Path:
    return runs_dir.resolve().parent.parent


def _resolve(path: str | Path, root: Path) -> Path:
    p = Path(path)
    return p if p.is_absolute() else root / p


def load_run_definition(run_id: str, runs_dir: Path = DEFAULT_RUNS_DIR) -> RunDefinition:
    """Rule 2: a run without a matching laptop-side definition is rejected."""
    path = run_definition_path(run_id, runs_dir)
    if not path.exists():
        existing = sorted(p.stem for p in runs_dir.glob("*.yaml")) if runs_dir.exists() else []
        raise RunRejected(
            f"no laptop-side run definition for run_id {run_id!r} (expected {path}). "
            f"run_id is typed by hand on the phone - check it for typos. Known run ids: {existing or 'none'}"
        )
    doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for key in ("run_id", "frames", "displayed", "clip_check"):
        if key not in doc:
            hint = " (create run definitions with `python -m prism_share.ingest.rundef new`)" if key == "clip_check" else ""
            raise RunRejected(f"{path}: required key '{key}' is missing{hint}")
    if doc["run_id"] != run_id:
        raise RunRejected(f"{path}: run_id inside the file is {doc['run_id']!r}, expected {run_id!r}")
    condition = doc.get("condition") or {}
    if not isinstance(condition, dict) or not all(isinstance(v, str | int | float | bool) for v in condition.values()):
        raise RunRejected(f"{path}: 'condition' must map names to scalar values")

    displayed = doc["displayed"]
    displayed = displayed if isinstance(displayed, list) else [displayed]
    if len(displayed) != 1 or isinstance(displayed[0], bool) or not isinstance(displayed[0], int):
        raise RunRejected(
            f"{path}: 'displayed' must be exactly one block_id, got {doc['displayed']!r}. A measurement run holds one "
            "static frame for the whole capture; cover content variation with one run per frame."
        )
    block_id = displayed[0]

    root = _root(runs_dir)
    clip_check = _parse_clip_check(doc["clip_check"], path, root)
    frames_dir = _resolve(doc["frames"], root)
    meta_path = frames_dir / "frames.json"
    if not meta_path.exists():
        raise RunRejected(f"{path}: {meta_path} not found (write it with `display frames`)")
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    params = CodecParams.from_dict(meta["params"])
    if params.fingerprint() != meta["params_fingerprint"]:
        raise RunRejected(f"{meta_path}: params fingerprint does not match its params (older frame format?)")
    recorded = {int(f["block_id"]): f for f in meta["frames"]}
    if block_id not in recorded:
        raise RunRejected(f"{path}: displayed block_id {block_id} is not in {meta_path}")

    payload = _payload(meta["payload"], root)
    frame = encode_frames(payload, params, n_frames=block_id + 1)[block_id]
    if image_sha256(frame.image) != recorded[block_id]["image_sha256"]:
        raise RunRejected(
            f"{meta_path}: re-encoding block {block_id} does not reproduce the displayed frame. "
            "The codec has changed since this run was displayed; the ground truth cannot be trusted."
        )
    shown = DisplayedFrame(block_id, frame.frame_index, recorded[block_id]["file"], frame.glyphs, frame.colours)
    return RunDefinition(run_id, path, frames_dir, params, shown, dict(condition), clip_check)


def _parse_clip_check(doc: Any, path: Path, root: Path) -> tuple[ClipCheck, ...]:
    if not isinstance(doc, dict) or set(doc) != set(CLIP_CHECK_ROLES):
        raise RunRejected(f"{path}: 'clip_check' must have exactly {list(CLIP_CHECK_ROLES)}")
    out = []
    for role in CLIP_CHECK_ROLES:
        entry = doc[role]
        missing = [k for k in _CLIP_CHECK_KEYS if not isinstance(entry, dict) or k not in entry]
        if missing:
            raise RunRejected(f"{path}: clip_check.{role} is missing {missing}")
        out.append(ClipCheck(role, int(entry["colour_depth"]), int(entry["cell_px"]), _resolve(entry["frames"], root),
                             float(entry["frame_mean_linear"]), float(entry["stops_vs_reference"])))
    return tuple(out)


def _payload(spec: dict[str, Any], root: Path) -> bytes:
    if "keystream" in spec:
        ks = spec["keystream"]
        return keystream(int(ks["seed"]), str(ks["domain"]), int(ks["bytes"]))
    if "file" in spec:
        p = _resolve(spec["file"], root)
        data = p.read_bytes()
        if hashlib.sha256(data).hexdigest() != spec["sha256"]:
            raise RunRejected(f"payload file {p} does not match the sha256 recorded at display time")
        return data
    raise RunRejected(f"unknown payload source {sorted(spec)}")


# --------------------------------------------------------------------------- #
# Writing run definitions
# --------------------------------------------------------------------------- #


def write_clip_check_frames(params: CodecParams, out_dir: Path) -> Path:
    """One deterministic frame of ``params`` for clip-checking (written once, reused by every run)."""
    folder = out_dir / f"c{params.colour_depth}_px{params.cell_px}"
    if (folder / "frames.json").exists():
        return folder
    from prism_share.codec.framing import frame_capacity

    payload = keystream(params.seed, _CLIP_PAYLOAD_DOMAIN, frame_capacity(params).block_bytes)
    frames = encode_frames(payload, params, n_frames=1)
    paths = save_frames([f.image for f in frames], folder)
    doc = {
        "purpose": "clip check only - never a measurement",
        "params": params.to_dict(),
        "params_label": params.label,
        "params_fingerprint": params.fingerprint(),
        "payload": {"length": len(payload), "keystream": {"seed": params.seed, "domain": _CLIP_PAYLOAD_DOMAIN,
                                                          "bytes": len(payload)}},
        "frames": [{"file": p.name, "block_id": f.header.block_id, "frame_index": f.frame_index,
                    "image_sha256": image_sha256(f.image)} for p, f in zip(paths, frames, strict=True)],
    }
    (folder / "frames.json").write_text(json.dumps(doc, indent=1) + "\n")
    return folder


def new_run_definition(run_id: str, frames: Path, block_id: int, condition: dict[str, Any], *,
                       runs_dir: Path = DEFAULT_RUNS_DIR, clip_dir: Path = DEFAULT_CLIP_CHECK_DIR,
                       overwrite: bool = False) -> Path:
    """Write experiments/runs/<run_id>.yaml with its clip-check pair, and the clip-check frames."""
    from prism_share.transmit.reference import extreme_configurations

    path = run_definition_path(run_id, runs_dir)
    if path.exists() and not overwrite:
        raise FileExistsError(f"{path} exists; run ids are join keys and are never silently reused")
    root = _root(runs_dir)
    meta = json.loads((_resolve(frames, root) / "frames.json").read_text(encoding="utf-8"))
    if block_id not in {int(f["block_id"]) for f in meta["frames"]}:
        raise ValueError(f"block_id {block_id} is not in {frames}/frames.json")
    frame_px = int(meta["params"]["frame_px"])
    clip = {}
    for role, row in zip(CLIP_CHECK_ROLES, extreme_configurations(), strict=True):
        params = CodecParams(colour_depth=row.colour_depth, cell_px=row.cell_px, frame_px=frame_px)
        folder = write_clip_check_frames(params, _resolve(clip_dir, root))
        clip[role] = {"colour_depth": row.colour_depth, "cell_px": row.cell_px, "frames": _relative(folder, root),
                      "frame_mean_linear": round(row.frame_mean, _LUMINANCE_DECIMALS),
                      "stops_vs_reference": round(row.stops_vs_reference, _STOPS_DECIMALS)}
    doc = {"run_id": run_id, "frames": str(frames), "displayed": [block_id], "condition": condition, "clip_check": clip}
    runs_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(doc, sort_keys=False))
    return path


def _relative(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root))
    except ValueError:
        return str(path)


def _scalar(text: str) -> str | int | float | bool:
    value = yaml.safe_load(text)
    return value if isinstance(value, str | int | float | bool) else text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Laptop-side run definitions.")
    sub = parser.add_subparsers(dest="command", required=True)
    n = sub.add_parser("new", help="write a run definition with its clip-check pair")
    n.add_argument("--run-id", required=True)
    n.add_argument("--frames", required=True, help="folder written by `display frames`")
    n.add_argument("--block", type=int, required=True, help="the one block_id this run holds on screen")
    n.add_argument("--condition", action="append", default=[], metavar="NAME=VALUE")
    n.add_argument("--runs-dir", default=str(DEFAULT_RUNS_DIR))
    n.add_argument("--clip-dir", default=str(DEFAULT_CLIP_CHECK_DIR))
    n.add_argument("--overwrite", action="store_true")
    args = parser.parse_args(argv)
    condition = {}
    for item in args.condition:
        name, _, value = item.partition("=")
        condition[name] = _scalar(value)
    path = new_run_definition(args.run_id, Path(args.frames), args.block, condition, runs_dir=Path(args.runs_dir),
                              clip_dir=Path(args.clip_dir), overwrite=args.overwrite)
    doc = yaml.safe_load(path.read_text())
    print(f"wrote {path}")
    for role in CLIP_CHECK_ROLES:
        c = doc["clip_check"][role]
        print(f"  clip-check {role}: {c['colour_depth']} colours, {c['cell_px']} px ({c['stops_vs_reference']:+.3f} stops) -> {c['frames']}")
    print(f"  display with: python -m prism_share.transmit.display measure {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
